[package]
name = "outline"
version = "0.1.2"
authors = ["Cameron Eldridge <cameldridge@gmail.com>"]
description = "\"Good enough\" literate programming tool"
homepage = "https://github.com/oinkiguana/outline"
repository = "https://github.com/oinkiguana/outline"
license = "MIT"
exclude = ["examples/*"]
edition = "2018"

[lib]
name = "outline"
path = "src/lib.rs"

[features]
bin = ["clap", "toml"]

[[bin]]
name = "outline"
path = "src/bin/main.rs"
required-features = ["bin"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[dependencies.toml]
version = "0.4"
optional = true

[dependencies.clap]
version = "2.32"
optional = true
